### ISSUE TITLE
new installation, no webgui available on OMV 5 

### ISSUE THREAD

**Issue by federicocappelli** [linuxserver/docker-duplicati#37]
I've just installed the Duplicati container using portainer.
The container is up and running and the webgui is supposed to be available at http://192.xxx.xxx.xxx:9001 but nothing is available at that address.
I used port 9001 because the 8200 was already in use by miniDLNA on OMV5

## Expected Behavior
Webgui up and running

## Current Behavior
No webgui available

## Environment
**OS:** Raspberry pi OS
**CPU architecture:** raspberry pi - arm64
**How docker service was installed:**
This is the stack I've used for creating the container:

```
---
version: "2.1"
services:
  duplicati:
    image: ghcr.io/linuxserver/duplicati
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/London
      #- CLI_ARGS= #optional
    volumes:
      - /srv/dev-disk-by-label-hdvac2/config:/config
      - /srv/dev-disk-by-label-hdvac2/backups:/backups
      - /srv/dev-disk-by-label-hdvac1/photos:/source
    ports:
      - 9001:9001
    restart: unless-stopped
```

## Docker logs
```
docker logs duplicati
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```
