### ISSUE TITLE
Failed to connect: | Google Drive

### ISSUE THREAD

**Issue by tho7o** [linuxserver/docker-duplicati#38]
---
name: Failed to Connect to Google Drive
about: I'm trying to config a backup task to upload de backups to Google Drive, but just allow set the empty PATH or '/' on detination Path configuration

---
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Duplicati should connect with Google Drive successfully using the path that i configure on the input PATH (destination).

## Current Behavior

When i set 

```
Path on server: /
```

the Test Connection say:
**Success: Connection worked!**

But if i try to change this path to:

```
Path on server: /backups
```
or
```
Path on server: /backups/
```
or
```
Path on server: backups
```
the Test Connection say:
**Error: Failed to connect:**

## Steps to Reproduce

1. it is happening just when i put a different path that '/' or *empty path*

## Environment
**OS:**
** OS ** Ubuntu 18
**CPU architecture:** x86_64
**How docker service was installed:**

from the official docker repo. This is my compose:

```
version: "2.1"

services:
  duplicati:
    image: ghcr.io/linuxserver/duplicati
    container_name: DUPLICATI
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./config:/config
      - ../WWW/mysql:/backups

    restart: unless-stopped
    ports:
      - 8200
      
    networks:
      default:
        ipv4_address: 21.21.21.49

networks:
  default:
    external:
      name: reverse-proxy-network
```

## Command used to create docker container (run/create/compose/screenshot)

```
docker-compose up -d
```

## Docker logs

```
failed to connect to Google Drive
```
