### ISSUE TITLE
Consider using MONO_EXTERNAL_ENCODINGS

### ISSUE THREAD

**Issue by jperez-nexus** [linuxserver/docker-duplicati#40]
Hello everyone,
We are trying to make huge backups (100G ~) using this docker-duplicati and we are having trouble with files with caracters like: ç, `, ´, and so on, but we are getting errors like this:

```
duplicati    | mono_w32file_find_next: Bad encoding for '.../pollen+�a.jpg'
duplicati    | Consider using MONO_EXTERNAL_ENCODINGS
```

It seems to be the same issue reported 5 years ago in the duplicati's official github, which is still unsolved:
https://github.com/duplicati/duplicati/issues/1241

So we are trying to solve by ourselves the bug. We've tried to make a new Dockerfile setting the env lang variables to es_ES.UTF-8 and setting the environment variable MONO_EXTERNAL_ENCODINGS=UTF-8 in the docker-compose.yaml, check it out:

**Dockerfile**
```
FROM ghcr.io/linuxserver/duplicati

RUN sed -i -e 's/# es_ES.UTF-8 UTF-8/es_ES.UTF-8 UTF-8/' /etc/locale.gen \
        && dpkg-reconfigure --frontend=noninteractive locales \
        && update-locale LANG=es_ES.UTF-8 \
        && update-locale LANGUAGE=es_ES.UTF-8

ENV LANG es_ES.UTF-8
ENV LANGUAGE es_ES.UTF-8
```

**Docker-compose**
```
---
version: "2.1"
services:
  duplicati:
    image: our-own-registry/duplicati:dev
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - MONO_EXTERNAL_ENCODINGS=UTF-8
      # - CLI_ARGS= #optional
    volumes:
      # - </path/to/appdata/config>:/config
      - /backups:/backups
      - source:/source
    ports:
      - 8200:8200
    restart: unless-stopped
```

But it still doesn't work. We don't know how to keep going. Of course change the file names is a solution, and we will work to normalize the names, but these files are from many people from a lot of projects so it's not a solution by now.
