### ISSUE TITLE
-run-script fails with "Native error= Access denied"

### ISSUE THREAD

**Issue by yatadev** [linuxserver/docker-duplicati#42]
I have a script with 777 rights:
```
#!/bin/bash
echo hallo
exit 1
```
The script is mounted into the container and owned by the user who is defined in the docker-compose file.
I run the container as root (i know..) but i tested normal user also with the same behaviour.

## Expected Behavior
The backup job should execute the bash script.

## Current Behavior
The backup job failes with "ApplicationName='/scripts/test.sh', CommandLine='', CurrentDirectory='', Native error= Access denied"

## Steps to Reproduce

docker-compose.yml file:

```
version: "2.1"
services:
  duplicati:
    image: ghcr.io/linuxserver/duplicati
    container_name: duplicati
    environment:
      - PUID=0
      - GUID=0
      - TZ=Europe/Berlin
      # this cli_args do not work.. no logfile
      - CLI_ARGS= --log-level=debug,--log-file=/config/duplicati.log
    volumes:
      - ./config:/config
      - ./scripts:/scripts
      - /data/backup/duplicati:/backups
      - /data/docker:/source
    restart: unless-stopped
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.duplicati.entrypoints=https"
      - "traefik.http.routers.duplicati.rule=Host(`duplicati.example.io`)"
      - "traefik.http.routers.duplicati.tls=true"
      - "traefik.http.routers.duplicati.tls.certresolver=le"
      - "traefik.docker.network=traefik-network"
      - "traefik.http.services.duplicati.loadbalancer.server.port=8200"
      - "traefik.http.routers.duplicati.middlewares=chain-authelia@file"
networks:
  traefik-network:
    external:
      name: traefik-network
```

## Environment
**OS:**
**CPU architecture:** x86_64
**How docker service was installed:**

Docker was installed from official docker repo
Version: 20.10.7

## Docker log
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    0
User gid:    0
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

```
