### ISSUE TITLE
Existing install, no web gui

### ISSUE THREAD

**Issue by danielmbrown603** [linuxserver/docker-duplicati#44]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Webgui up and running. Webgui was accessible as of a few days ago.  Not sure what to do, any help is appreciated. Thank you

## Current Behavior
No webgui available

```
This page isn’t working
If the problem continues, contact the site owner.
HTTP ERROR 400
```

## Environment
**OS:** 
Synology DSM 7
**CPU architecture:** x86_64/arm32/arm64 
x86_64 Ryzen DS1821+
**How docker service was installed:**
docker-composer outlined below

## Command used to create docker container (run/create/compose/screenshot)

```
  duplicati:
    image: lscr.io/linuxserver/duplicati
    container_name: duplicati
    environment:
      TZ: $TIME_ZONE
      PUID: $PUID
      PGID: $PGID
      #  - CLI_ARGS= #optional
    labels: 
      - com.centurylinklabs.watchtower.enable="true" # Watchtower automated update label
    ports:
      - 8200:8200
    volumes:
      - $PERSIST/duplicati/config:/config
      - $MEDIA/:/source:ro
    restart: unless-stopped
```

## Docker logs

```
today at 1:24:25 PM[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
today at 1:24:25 PM[s6-init] ensuring user provided files have correct perms...exited 0.
today at 1:24:25 PM[fix-attrs.d] applying ownership & permissions fixes...
today at 1:24:25 PM[fix-attrs.d] done.
today at 1:24:25 PM[cont-init.d] executing container initialization scripts...
today at 1:24:25 PM[cont-init.d] 01-envfile: executing... 
today at 1:24:25 PM[cont-init.d] 01-envfile: exited 0.
today at 1:24:25 PM[cont-init.d] 01-migrations: executing... 
today at 1:24:25 PM[migrations] started
today at 1:24:25 PM[migrations] no migrations found
today at 1:24:25 PM[cont-init.d] 01-migrations: exited 0.
today at 1:24:25 PM[cont-init.d] 10-adduser: executing... 
today at 1:24:25 PM
today at 1:24:25 PM-------------------------------------
today at 1:24:25 PM          _         ()
today at 1:24:25 PM         | |  ___   _    __
today at 1:24:25 PM         | | / __| | |  /  \ 
today at 1:24:25 PM         | | \__ \ | | | () |
today at 1:24:25 PM         |_| |___/ |_|  \__/
today at 1:24:25 PM
today at 1:24:25 PM
today at 1:24:25 PMBrought to you by linuxserver.io
today at 1:24:25 PM-------------------------------------
today at 1:24:25 PM
today at 1:24:25 PMTo support LSIO projects visit:
today at 1:24:25 PMhttps://www.linuxserver.io/donate/
today at 1:24:25 PM-------------------------------------
today at 1:24:25 PMGID/UID
today at 1:24:25 PM-------------------------------------
today at 1:24:25 PM
today at 1:24:25 PMUser uid:    1024
today at 1:24:25 PMUser gid:    101
today at 1:24:25 PM-------------------------------------
today at 1:24:25 PM
today at 1:24:25 PM[cont-init.d] 10-adduser: exited 0.
today at 1:24:25 PM[cont-init.d] 30-config: executing... 
today at 1:24:25 PM[cont-init.d] 30-config: exited 0.
today at 1:24:25 PM[cont-init.d] 90-custom-folders: executing... 
today at 1:24:25 PM[cont-init.d] 90-custom-folders: exited 0.
today at 1:24:25 PM[cont-init.d] 99-custom-scripts: executing... 
today at 1:24:25 PM[custom-init] no custom files found exiting...
today at 1:24:25 PM[cont-init.d] 99-custom-scripts: exited 0.
today at 1:24:25 PM[cont-init.d] done.
today at 1:24:25 PM[services.d] starting services
today at 1:24:25 PM[services.d] done.
```
