### ISSUE TITLE
How can I set the webservice interface ip?

### ISSUE THREAD

**Issue by Zoubi** [linuxserver/docker-duplicati#8]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

By default the duplicati web server listens on 0.0.0.0 and I can't access it since I'm running it on a headless machine.
How can I add the options --webservice-interface=IP_ADDRESS in this docker file?

It's  quite new to me :)

Thanks !

**Comment by aptalca** [comment]
You map port 8200 in docker run/create and then you can access in that port through the host ip

**Comment by Zoubi** [comment]
Unfortunately it does not work.

I have this docker-compose:

```
  duplicati:
    image: linuxserver/duplicati:latest
    container_name: duplicati
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8200:8200
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${HOME}/.config/duplicati:/config
      - /var/media:/backups
      - /var/media:/source
      - /etc/localtime:/etc/localtime:ro
```

And when I want to access the webservice on 192.168.0.1:8200 the browser keeps waiting and nothing shows up.
